## Soziale Netzwerkanalyse {#sna}
Neben der Topic-Analyse stellt die Untersuchung der Interaktionen zwischen Nutzern eines Online Social Networks (OSN) die zweite Säule dieser Arbeit dar.
Diese Interaktionen lassen sich mit Methoden der sozialen Netzwerkanalyse (SNA) untersuchen.

Im Gegensatz zu traditionellen Ansätzen soziologischer Forschung betrachtet die SNA nicht das Individuum "für sich" sondern Zusammenschlüsse mehrerer Individuen.
Insbesondere geht sie davon aus, dass *Akteure* Beziehungen zueinander aufbauen, und dass dieses Beziehungsgeflecht strukturelle Eigenschaften aufweist, die sich analysieren lassen.
"Sozial" werden diese Beziehungen dadurch, dass als Akteure Individuen oder deren Zusammenschluss in Form von Gruppen und Organisationen in Frage kommen.
Ein soziales Netzwerk beschreibt also eine endliche Zahl an Akteuren sowie deren Beziehungen zueinander.
Das Ziel dieser Sichtweise besteht darin, Eigenschaften der soziostrukturellen Umwelt zu verstehen und wie diese mit Merkmalen auf Akteursebene interagieren.
Sie bietet damit eine Alternative zu traditionellen Ansätzen, die das Individuum als einzelne, unabhängige Einheit betrachten.

Die Darstellung solcher Akteur-Netzwerke kann auf verschiedene Weise erfolgen.
Eine seit den Anfängen soziometrischer Forschung verbreitete Form stellt die Soziomatrix dar, in der die Zeilen und Spalten einer Matrix auf Akteure verweisen (vgl. [@Wasserman1994, S. 70]); der Wert in Zeile $i$ und Spalte $j$ zeigt an, ob Zwischen Akteuren $i$ und $j$ eine Verbindung besteht oder nicht, bzw. wie viele Verbindungen bekannt sind wenn nicht nur binäre Beziehungen (vorhanden/nicht vorhanden) codiert werden.
Diese Darstellungsform entspricht damit der Adjazenzmatrix eines Graphen, die wiederum auf dem mathematischen Teilgebiet der Graphentheorie genutzt wird.  
Die Darstellung sozialer Beziehungen als Graph stellt indes eine weitere Form der Modellierung sozialer Netzwerke dar.

#### Graphen
Bei einer Darstellung in Form eines Graphen werden Akteure als Knoten und Beziehungen zwischen ihnen als Kanten aufgefasst; mittels Adjazenzlisten bzw. -matrizen lassen sich diese Graphen kompakt darstellen.
Die Graphentheorie bietet nicht nur eine adäquate Darstellung der Idee von untereinander verbundenen Akteuren; sie stellt auch Konzepte bereit, um die Eigenschaften sozialer Netzwerke untersuchen und beschreiben zu können.
Graphen lassen sich formal als die endliche, nicht-leere Menge von Knoten $V$ beschreiben, welche über Kanten aus der Menge $E \subseteq V \times V$ aller geordneten Knotenpaare miteinander verbunden sind.
Da $E$ geordnete Paare von Knoten $(u,v) \in V$ enthält, spricht man von einer gerichteten Kante von $u$ nach $v$; ferner ist $E$ eine Multimenge, enthält also Paare von Knoten mehrfach (vgl. [@Brandes2012]).
Durch die Darstellung als gerichteter Multigraph lassen sich nicht nur gerichtete Graphen mit Mehrfachkanten realisieren, auch ungerichtete Graphen lassen sich auf diese Weise darstellen, indem zwei einander entgegengesetzte gerichtete Kanten zu einer zusammengefasst werden.

#### Grad von Knoten
Sind zwei Knoten über eine oder mehrere Kanten miteinander verbunden, sind sie "Nachbarn"; die Zahl der Nachbarn eines Knotens bezeichnet man als dessen Grad.
Knoten $v$ in einem gerichteten Graphen besitzen einen Ausgangsgrad $d^{+}(v)$, der die Anzahl ausgehender Kanten $(v,w) \in E$ angibt, sowie einen Eingangsgrad $d^{-}(v)$, der der Zahl eingehender Kanten $(v,w) \in E$ entspricht (vgl. [@Brandes2012]); der Grad eines Knotens entspricht der Summe aus Eingangs- und Ausgangsgrad.
Der Grad eines Knotens gibt im Kontext sozialer Netzwerke Aufschluss über die Zahl der Beziehungen, die ein Akteur zu anderen ausbildet, und kann daher als Maß für die Aktivität des Akteurs gesehen werden (vgl. [@Wasserman1994] S.100).
In dieser Arbeit werden Betrachtungen des Knotengrads angestellt, um festzustellen, wie aktiv ein Nutzer sich mit anderen in derselben Community austauscht.

\todo{Beispielgraph, butterfly oder so}

#### Egozentrische Netzwerke
Wird anstatt das Netzwerk *in toto* zu betrachten die Sichtweise eines einzelnen Akteurs eingenommen, spricht man von egozentrischen oder einfach Ego-Netzwerken.
Diese bestehen aus einem zentralen Knoten *Ego*, dessen Nachbarn oder *Alteri*, sowie den Beziehungen der Alteri untereinander.
Solche Strukturen, deren Sicht sich auf einen Ausschnitt um einen Akteur beschränkt, werden auch als "lokale" bzw. "persönliche Netzwerke" bezeichnet, da ihre Sicht lokal beschränkt und stark auf die Person des Ego ausgerichtet ist.
In dieser Arbeit werden Ego-Netzwerke genutzt, um Interaktionsgraphen eines Nutzers zu erstellen.
Der betrachtete Nutzer nimmt hier die Person des Ego ein, die Alteri sind alle weiteren Nutzer, mit denen er auf Reddit in Form von Kommentaren kommuniziert hat.
Diese Kommunikation kann einseitig von Ego oder den Alteri ausgehen, sie kann aber auch vom jeweils anderen erwidert werden; ebenso sind diese Kommunikationsakte nicht in ihrer Anzahl beschränkt, weshalb Kanten im Graph des Ego-Netzwerks als gerichtete Multikanten umgesetzt werden.
Da zudem einzig die Strukturen von Bedeutung sind, die sich zwischen Ego und Alteri manifestieren, werden die Beziehungen zwischen den Alteri außer Acht gelassen.

#### Reziprozität
Strukturen aus zwei Knoten eines Graphen und deren möglichen Verbindungen werden auch als *dyadische* Beziehung bezeichnet.
Dyaden kennen drei mögliche Zustände, die durch die Art der Verbindung der beiden Knoten bestimmt sind:

* Null-Dyade: Zwischen den beiden Knoten besteht keine Verbindung,
* Asymmetrische Dyade: Eine einzelne Kante verbindet die beiden Knoten, für Knoten $u,v$ entweder die Kante $(u,v)$ oder $(v,u)$ 
* Wechselseitige^[engl. "mutual"] Dyade: Die Verbindung wird von beiden Partnern erwidert, für Knoten $u,v$ also das **Paar** gerichteter Kanten $(u,v)$ **und** $(v,u)$ (bzw. in kompakterer Darstellung auch $u \leftrightarrow v$, vgl [@Wasserman1994, S. 510])

Die "nächstgrößere" Struktur, die sich beobachten ließe, stellen *Triaden* dar, also Muster bestehend aus drei Knoten.
Für diese Arbeit ist eine solche Betrachtung wenig zielführend, da eine Triade immer Ego als einen Eckpunkt enthalten wird oder die Null-Triade ist (zur Erinnerung: Verbindungen unter den Alteri werden hier nicht berücksichtigt).
Aus letzterer Beobachtung lässt sich kein Schluss ziehen, da sie durch das das Forschungsdesign bedingt ist; erstere Betrachtung zerfällt immer in die Betrachtung zweier dyadischer Beziehungen, die Ego enthalten.

Von besonderem Interesse ist die Frage, ob Dyaden von Ego und Alteri zu wechselseitigen Beziehungen neigen, oder ob es sich eher um einseitige Verbindungen handelt.
Da eine Kante zwischen Nutzern eine Kommunikationshandlung darstellt entsprechen asymmetrische Dyaden Interaktionen, die nicht erwidert werden.
Bei wechselseitigen Interaktionen liegt hingegen ein Rede-Gegenrede-Akt vor, die Aktion des einen provoziert eine Reaktion des anderen Partners.

Die Betrachtung dieser Reziprozität von Beziehungen kann Aufschluss geben über die Art von Diskursen im lokalen Netzwerk eines Nutzers.
Um die Tendenz wechselseitiger Kanten zu bestimmen, nutzt diese Arbeit ein 1955 von Katz und Powell vorgeschlagenes Maß, einen "index of tendency toward reciprocation"\ [@Katz1955].
Dieser Index $\rho_{KP}$ lässt sich entweder für ein festes oder ein freies Design bilden ("fixed choice" v. "free choice"), abhängig davon, ob alle Knoten nur eine bestimmte Zahl an Beziehungen ausbilden dürfen, oder ob deren Zahl unbeschränkt ist.
Da Reddit-Nutzer in der Wahl ihrer Kommunikationspartner keinen Einschränkungen unterliegen, nutzt diese Arbeit den Index für ein freies Design; für eine Beschreibung des festen Falls sei auf die Literatur verwiesen ([@Katz1955], [@Wasserman1994]).

#### Katz-Powell-Index
In Ermangelung einer angemessen prägnanten Übersetzung wird statt der Bezeichnung im ursprünglichen Aufsatz hier die Umschreibung "Katz-Powell-Index" oder, wo angemessen, schlicht $\rho_{KP}$ verwendet.  
Der Index stellt eine Abschätzung der Wahrscheinlichkeit dar, dass zwei Akteure gegenseitige Kanten ausbilden.
Formal lässt sich dies als Wahrscheinlichkeit  auffassen, dass eine Kante $(u,v)$ und deren Gegenstück $(v,u)$ existieren (vgl. [@Wasserman1994], S. 515). Es folgt aus der Definition der bedingten Wahrscheinlichkeit:
\begin{equation}
P(u \to v \wedge v \to u) = P(u \to v)P(v \to u|u\to v)
(\#eq:probmut)
\end{equation}

Die Idee von Katz und Powell besteht darin, den letzten Term von \@ref(eq:probmut) als gewichtete Summe von Wahrscheinlichkeiten darzustellen.
Dazu führen sie einen Faktor $\rho_{KP}$ ein (vgl. [@Wasserman1994]):
  
\begin{equation}
P(v \to u|u\to v) = P(v \to u) + \rho_{KP}P(v \nrightarrow u)
(\#eq:rhomut)
\end{equation}

Der Faktor $\rho_{KP}$ spiegelt also die Tendenz wider, mit der eine gegeben Kante $(u,v)$ erwidert wird, er bildet einen "index of tendency toward reciprocation"\ [@Katz1955].
Anhand der Formulierung in \@ref(eq:rhomut) lassen sich verschiedene Werte für $\rho_{KP}$ betrachten (vgl. [@Wasserman1994]):

* $\rho_{KP} = 0$: damit gilt automatisch $P(v \to u|u\to v) = P(v \to u)$, die bedingte Wahrscheinlichkeit ist gleich der unbedingten, die beiden Ereignisse sind unabhängig; eine Tendenz, Kanten zu erwidern, besteht nicht
* $\rho_{KP} = 1$: dann gilt wegen der Summe der Wahrscheinlichkeiten für Ereignis und Gegenereignis auch $P(v \to u|u\to v) = 1$, alle Kanten werden erwidert; gegeben eine Kante $(u,v)$ wird beobachtet beträgt die Wahrscheinlichkeit 1, dass auch $(v,u)$ beobachtet wird

Der Index wird immer für ein Netzwerk als ganzes berechnet.
Sei dazu $g$ die Anzahl der Akteure in diesem Netz.
Jeder Akteur kann $(g - 1)$ Kanten zu anderen ausbilden.
Sei $x_i$ der Ausgangsgrad eines Knotens $i$, dann ist die Wahrscheinlichkeit, dass zwei Knoten $i, j$ eine gemeinsame Kante ausbilden $\frac{x_i x_j}{(g-1)^2}$.
Bezeichne $L$ die Summe aller Ausgangsgrade $L = \sum{x_i}$ und $L_2$ die Summe deren Quadrate $L = \sum{x_i^2}$, und sei $M$ die Gesamtzahl aller beobachteten wechselseitigen Kanten.
Dann lässt sich die Größe $\rho_{KP}$ abschätzen^[Eine Herleitung dieser Abschätzung ist nicht trivial und wird hier nicht wiedergegeben, sondern ist [@Katz1955] zu entnehmen.] als

\begin{equation}
\rho_{KP} = \frac{2(g-1)^2M-L^2+L_2}{L(g-1)^2-L^2+L_2}
(\#eq:rhokp)
\end{equation}

Die Werte dieses Index bewegen sich in $-\infty < \rho_{KP} \leq 1$.
Ein Wert von 0 bedeutet, dass keine Tendenz zu wechselseitigen Kanten erkennbar ist; ein Wert von 1 signalisiert maximale Tendenz, alle Kanten werden erwidert.
Nimmt der Index negative Werte an, bedeutet dies, dass weniger wechselseitige Dyaden beobachtet wurden als in einem rein dem Zufall unterworfenen Prozess möglich wären; es liegt die gegenteilige Tendenz vor, hin zu asymmetrischen bzw. Null-Dyaden.

Diese Arbeit betrachtet den Katz-Powell-Index lokaler Ego-Netzwerke, um zu beobachten, ob Kommunikationsbeziehungen eher wechselseitig interaktiv, oder einseitig angelegt sind.
Dadurch lässt sich beispielsweise untersuchen, ob ein Ego in einem Netz, das mehrheitlich aus Alteri mit den gleichen Interessen wie Ego besteht, dazu neigt, Verbindungen wechselseitig anzulegen als etwa in einem Umfeld, das seine Interessen nicht teilt.

#### Longitudinale Untersuchung

Abschließend sei darauf hingewiesen, dass diese Arbeit eine Longitudinalstudie der in diesem Kapitel beschriebenen Maße darstellt.
Indem die Veränderung bspw. des Knotengrads über die Zeit betrachtet wird, lässt sich feststellen, ob ein Nutzer eher in seinem Kommunikationsverhalten aktiver wird (Grad nimmt zu), oder ob er dieses eher einschränkt.

<!--
----------------------

zudem betrachten wir veränderungen struktureller eigenschafte über die zeit hinweg

katz-powell $\rho_{KP}$, to measure the tendency for actors in a group to reciprocate choices mroe freqeuently than would occur simply by chance; dimensionslos, 0 und 1 als benchmarks; 0: keine reziprocitat, 1, alle kanten reziprok); kleienr 0: zu wenige gegenseitige dyaden (mutual dyads), "less than chance tendency toward reciprocation", negative "tendencies away from mutual dyads toward asymmetric and nulls"

fiexed choice, free choice, kommt auf design der datenerhebung an; in usnerem fall keine auskunft von akteur (ego), daher freie wahl

formel (Wf 517)

--------------------

Die soziale Netzwerkanalyse betrachtet Beziehungen zwischen Akteuren 
Beziehungen als Verbindungen zwischen Einheiten sind Bestandteil von Netzwerktheorie
Betrachtungseinheit ist nicht das Individuum, sondern eine Menge von Individuen und deren VErbindung untereinander

"The task is to understand properties of the social (economic or political) structural environment, and how these structural properties influence observerd characteristics and associations among characteristics" (WassermanFaust, S.8)

"auxiliary network studies": network theories and measurements become explanatory factors or variables in understanding individual behavior (WF, S. 9)

betrachtet muster in beziehungen die sich zwischen akteuren ausbilden

Moreno und das Sozogramm als beginn der soziometrie (Moreno 1934)

alternative betrachtugnsweise zum unabhängigen individuum

matheamtische Grundlagen: graphentheorie, wahrscheinlichkeitstheorie, algebren (algebraische modelle)

graphentheorie bietet angemessene darstellung eines sozialen entzwerks sowie konzepte die genutzt werden können, eigenschaften sozialer entzwerke zu untersuchen

neben graph-darstellung auch sociometric notation (sociomatrix, zeilen und spalten sind akteure)

graph, knoten, kanten

kanten gerichtet, ungerichtet

Brandes:
Graph menge an Kanten und Knoten, blabla

soziales netzwerk besteht aus endlicher zahl an akteuren und deren beziehungen zueinander. 

Akteur, endpuntke von beziehungen; individuelle oder kollektive einheiten

graph darstellung entspricht den konzepten von akteuren und deren verbindung und liefert mathematsich begründete und erprobte verfahren, um strukturelle eigenschaften zu messen

one-mode (unimodal) wenn alle akteure gleicher art sind (nutzer eines OSN)

Knotengrad, Eingang, Ausgang

mean degree? 2L/g

egozentrische oder ego-netzwerke, zentraler akteur "ego", "alteri" zu denen er beziehungen pflegt, sowie beziehungen der alteri untereinander

heissen auch "personal network"

dyade, dyadische beziehung, zwei akteure



da egonetz, hauptsächlich untersuchung von dyaden

drei typen von dyaden: mutual (gegenseitig, i->j und j->i)
asymmetrisch, i->j oder j->i
null-dyade, keine verbindung; alteri untereinander

-->