\cleardoublepage
## Diskussion {#diskussion}

In den vorangegangenen Kapiteln wurde das Resultat der Topic-Modellierung dargelegt sowie eine Fallstudie für zwei Nutzer vorgestellt, deren Ergebnisse hier noch einmal diskutiert und interpretiert werden sollen.
Zudem werden mögliche Ansätze für weitere Forschungsarbeit aufgezeigt.

### Topic-Model

#### Pre-processing der Daten
In Kapitel \@ref(meth-lda) wurde das methodische Vorgehen bei der Vorbereitung der Inhalte für ein LDA-Modell erläutert.
Es wurde erwähnt, dass eine Entfernung von Stoppwörtern nicht unternommen wurde.
Im erstellten Topic-Modell hatte dies zur Folge, dass sich einige Topics nicht trennscharf als eigenständige Community abgrenzen ließen.
Dabei lässt sich nicht pauschal feststellen, dass eine Entfernung von Stoppwörtern in einem besseren Modell resultiert.
Viele vorgefertigte Stoppwort-Listen enthalten Artikel und Personalpronomen.
Diese lassen jedoch Rückschlüsse auf die Psyche der Autoren zu.
Beispielsweise haben De Choudhury et al. [@DeChoudhury2016] festgestellt, dass sich vorhersagen lässt, ob ein Nutzer, der in seiner Online-Kommuniaktion psychische Erkrankungen thematisiert, in Zukunft auch Suizidvorstellungen thematisieren könnte.
Sie stellen dabei fest, dass Nutzer, die vermehrt Personalpronomen der 1. Person Singular verwenden, eher dazu neigen, ihren Diskurs hin zu suizadeln Themen zu verschieben; zugleich weist ihre Sprache weniger Pronomen der zweiten und dritten Person sowie der ersten Person Plural auf, was auf geringes Interesse an anderen Nutzern hindeutet.
Daher ist eine Evaluation sinnvoll, ob die Güte des Modells tatsächlich davon profitiert, diese Wörter zu entfernen.  
Gleiches gilt für weitere gängige Verfahren der Normalisierung von Texten, wie sie in der Computerlinguistik Anwendung finden, etwa dem *Stemming*, also der Reduzierung auf Stamm eines Wortes.

#### Textkorpus

Ebenso bietet es sich an, bei der Konstruktion des Korpus, auf dem das LDA-Modell bestimmt werden soll, weitere Inhalte zu berücksichtigen.
In dieser Arbeit wurden die Titel der obersten 50 Beiträge aus dem "Top"-Listing von Reddit herangezogen.
Dadurch ist gewährleistet, dass insbesondere auch ältere Beiträge nicht von der Betrachtung ausgeschlossen sind, denn "Top" liefert die best-bewerteten Beiträge aller Zeit.
Unter Umständen führt dies jedoch auch zu einer Verzerrung, da ältere Beiträge prinzipiell mehr Zeit hatten, Bewertungen zu sammeln.
Gegebenenfalls bietet es sich an, eine Stichprobe über alle Inhalte zu ziehen und daraus die Dokumente für das LDA-Modell zu erstellen.

#### Anzahl der Topics
Das LDA-Modell ist im Wesentlichen parametrisiert durch den Parameter $k$, der die Zahl der zu bestimmenden Topics festlegt.
Griffiths und Steyvers [@Griffiths2004] evaluieren unterschiedliche Modelle, die sich jeweils nur in der Wahl von $k$ unterscheiden.
Dazu schätzen sie die bedingte Wahrscheinlichkeit $P(w|T)$[^Blei et al. [@Blei2003] bezeichnen die Anzahl der Topics des Modells mit $k$, Griffiths und Steyvers weichen davon ab und wählen hierfür $T$] ab, dass ein durch $T$ parametrisiertes Modell die Wörter $w$ des Korpus erzeugt.
Ihr Korpus enthält nach Normalisierung 20.551 eindeutige und insgesamt 3.026.970 Wörter.
Sie variieren die Zahl der Topcis zwischen 50 und 1.000 und kommen zu dem Schluss, dass ein Modell mit $k = 300$ in ihrem Fall den höchsten Wert für $P(w|T)$ liefert.
Im Fall der vorliegenden Arbeit war eine solche Auswertung unterschiedlicher Modell-Konfigurationen nicht möglich, da die Größe des Datensatzes ungleich höher ist, als im Artikel von Griffiths und Steyvers.
Der vorliegende Subreddit-Korpus umfasst `r fmt(1488451)` eindeutige und `r fmt(52869917)` Wörter insgesamt; die damit einhergehende Laufzeit einer Evaluierung war nicht akzeptabel.
Das R-Package *ldatuning* [@R-ldatuning] setzt die Metrik nach Griffiths und Steyvers sowie einige weitere um und kann genutzt werden, verschiedene Modelle zu evaluieren.
Die Größe des Korpus hat dabei einen maßgeblichen Einfluss auf die Laufzeit der Evaluation.

#### Selbstreferentialität von Reddit

Ein problematisches, aber zugleich interessantes Topic, das im Modell identifiziert wurde, ist Topic 235.
Dieses enthält zu einem Großteil Stopp- und Füllwörter (siehe Tabelle \@ref(tab:app-top-words-lab) im Anhang).
Singer et al. [@Singer2014] stellen fest, dass im Gegensatz zur Anfangszeit von Reddit der Anteil sogenannter *self posts*, also von Nutzern selbst erstellte Inhalte, im Verlauf der Zeit zunimmt.
Sie bezeichnen dies als "Selbstreferentialität" (*self reference*) im Gegensatz zum Teilen von Links auf andere Inhalte.
Die schiere Größe von Topic 235 mit über 45.000 zugeordneten Subreddits könnte ein Effekt dieser Verschiebung in Richtung von Nutzern selbst erstellter Inhalte sein.
Ohne genauere Betrachtung bleibt dies jedoch nur eine Vermutung.
Ein möglicher erster Ansatz wäre etwa, die Art von Inhalten (Bild, Video, Text, Link) dieses Topics zu betrachten und den Anteil von *self posts* zu messen.  

### Interaktionsgraphen

Sowohl für monocasa als auch für cavedave wurden die monatlichen Interaktionsgraphen mit Methoden der sozialen Netzwerkanalyse untersucht.
Dabei wurden einige Maße bzw. Ideen skizziert, die hier noch einmal elaboriert werden sollen.
Einführend seien jedoch die Ergebnisse der beiden Analysen kurz zusammengefasst.

#### monocasa

Die Topic-Verläufe des Nutzers monocasa weisen im Zeitraum um Oktober 2013 zwei Zäsuren auf, die auf ein Verlassen von Topic 239 hindeuten.
Der Beobachtungszeitraum wurde daher zum Teil auf diese Phase fokussiert um zu ergründen, warum der Nutzer diese Community verlässt.
Bei der Suche nach möglichen Ursachen hierfür wurde gezeigt, dass zwischen den Anteilen der Alteri und der Kommentare des Nutzers eine mittlere bis starke Korrelation vorliegt.
Spearmans $\rho$ beträgt im Fall von Topic 239 den Wert 0.7 und ist auf dem 0.1%-Niveau statistisch signifikant, es bestehen also lineare Beziehungen bei der Monotonizität dieser Größen: höhere Werte der einen bringen höhere Werte der anderen mit sich.
Weiterhin wurde ein simples Maß für Attraktivität eines Topics entwickelt, das im Wesentlichen die Beobachtung bestätigt, dass Topic 239 zum Zeitpunkt des Austritts keine Anziehungskraft besitzt; dafür erreicht die Attraktivität von Topic 235 zu diesem Zeitpunkt ein globales Maximum.
Möglicherweise hat also ein anderes Topic das Interesse des Nutzers auf sich gezogen, sodass er ein anderes verlassen hat.

Für die monatlichen Snapshot-Graphen lässt sich die Zahl der Knoten und Kanten bestimmen und damit das Kommunikationsverhalten quantifizieren, denn die Knoten entsprechen individuellen Kommunikationspartnern, die Kanten der Anzahl an Kommentaren.
Im Oktober 2013 erreichen diese beiden Größen ein Minimum um 0; der Nutzer scheint also nicht nur ein Topic zu verlassen, sondern die Plattform allgemein.
Auch die Reziprozität erreicht in diesem Monat das globale Minimum, Kanten zwischen Ego und Alteri neigen dazu, eher asymmetrisch angelegt zu sein.

Die Feststellung, dass der Nutzer zu diesem speziellen Zeitpunkt die Plattform meidet, setzt sich auch bei der Betrachtung der thematischen Teilgraphen fort.
In diesen existieren Kanten ausschließlich zwischen Ego und solchen Alteri, die ein gemeinsames Interesse mit Ego aufweisen.
Bestimmt man zusätzlich die Reziprozität in diesen Teilgraphen, zeigt sich an der Stelle des Austritts ein Loch: der Graph weist keine Knoten auf, Ego teilt also mit keinem der Alteri ein Interesse.

An dieser Stelle lässt sich der Grund für ein Verlassen eines Topics bzw. der Plattform generell nicht konkret bestimmen.
Auffällig ist jedoch, dass in den beiden Monaten vor der Zäsur im Oktober 2013 der Interaktionsgraph vergleichsweise viele Kanten enthält, deren Zahl dann jäh auf 0 fällt.
Eine Betrachtung der Kommunikationsinhalte bzw. eine direkte Befragung des Nutzers könnte an dieser Stelle tieferen Einblick bieten; möglicherweise kam es zu einer Auseinandersetzung, auf die hin monocasa Reddit einstweilen verlassen hat; denkbar sind aber auch Ursachen im privaten Umfeld.
Eine endgültige Erklärung kann an dieser Stelle nicht gegeben werden.

#### cavedave

Über eine Betrachtung der Topic-Verläufe wurde festgestellt, dass der Nutzer cavedave zu Anfang in Topic 239 (Technologie- und IT-Themen) aktiv ist, diese Community jedoch nach einiger Zeit nahezu vollständig verlässt.
Ebenso war ersichtlich, dass die beiden Topics 219 (Wissenschaft) und 235 (Reddit) einander zwischen Januar 2012 und Januar 2014 effektiv ablösen.
Wie bei monocasa auch bestätigt sich die Vermutung der Korrelation der Anteile von Alteri und Kommentaren des Nutzers.
Spearmans $\rho$ gibt für die drei näher betrachteten Topics Werte zwischen 0.62 und 0.73 an, alle drei sind auf dem 0.1%-Niveau statistisch signifikant.  
Die Betrachtung der Anziehungskraft der Topics zeigt, dass die Attraktivität von Topic 239 ab etwa 2011 auf 0 fällt, woraufhin der Nutzer diese Community verlässt; die Anziehungskraft von Topic 235 hingegen nimmt deutlich zu, während die von 219 abnimmt, die beiden lösen sich sozusagen ab.  

Bei der Betrachtung der Größe der monatlichen Snapshot-Interaktionsgraphen fiel auf, dass im Zeitraum des Übergangs zwischen 219 und 235 generell eine Phase geringer Partizipation vorliegt, die erst endet, wenn der Nutzer ab etwa Mitte bis Ende 2013 in der neuen Community "angekommen" ist.
Ist diese Phase jedoch überwunden, steigert der Nutzer seine Aktivität erheblich, sowohl die Zahl der Knoten (Kommunikationspartner) als auch der Kanten (Kommunikationsakte) steigen stark an.
Ein Blick auf die Reziprozität der Interaktionsgraphen hat gezeigt, dass in dieser Phase ebenfalls geringe Tendenz besteht, Kanten zwischen Ego und Alteri zu erwidern, Interaktionen sind also meist einseitig angelegt; allerdings schwankt das Maß für Reziprozität teils erheblich und beginnt auch nach dem Übergang der beiden Topics nur langsam wieder zu steigen.

Differenziert man den gesamten Interaktionsgraphen in die einzelnen Topic-Communities, ergeben sich bei der Betrachtung der Reziprozität in diesen Teilgraphen im Zeitraum des Umbruchs deutliche Lücken, der Nutzer unterhält also keine Verbindungen mehr mit anderen Mitgliedern dieses Topics.
Eine Korrelation der Reziprozität und der Kommentar-Anteile für die individuellen Communities fällt indes eher schwach aus.
Bemerkenswert ist jedoch, dass die Reziprozität im monothematischen Teilgraphen, in dem nur Nutzer mit demselben Interesse wie Ego enthalten sind, in diesem Zeitraum des Übergangs leer ist.
Es scheitn so, als hätte der cavedave den Anschluss verloren und sein Interesse abgewandt, woraufhin eine Phase des Umbruchs folgt.
Diese Phase endet jedoch, als er sich der Community um Topic 235 anschließt.

Abermals ist es an dieser Stelle nicht möglich, eine abschließende und endgültige Erklärung zu liefern.
Die Ergänzung der quantitativen Analyse durch qualitative Forschungsmethoden scheint nötig, um sich der Ursache dieses thematischen Wandles nähern zu können.

#### Attraktivität von Topics

Um die Anziehungskraft eines Topics zu bestimmen, wurde ein naives Maß entwickelt, das sich aus dem Produkt der Topic-Anteile von Kommentaren eines Nutzers und seinen Alteri bildet.
Diesem Maß zugrunde liegt die Vermutung, dass sowohl das Interesse des Nutzers als auch sein Umfeld eine wichtige Rolle dabei spielen, ob er sich einer Community anschließt oder nicht.
Dabei erscheint es sinnvoll, in Zukunft noch weitere Größen zu berücksichtigen, etwa die Reziprozität der Kanten, oder Eigenschaften der Alteri wie etwa Prestige oder Grad.

#### Thematische Teilgraphen

Schränkt man die Sicht auf den Interaktionsgraphen eines Nutzers weiter ein und fordert, dass ausschließlich Kanten zu Alteri berücksichtigt werden, die mit Ego Interessen gemeinsam haben, lassen sich thematisch enger eingegrenzte Strukturen untersuchen.
Für diese thematischen Teilgraphen ließen sich beispielsweise Zentralitäts- und Verbundenheitsmaße bestimmen.
Damit ergäbe sich ein Blick auf eine Themen-Community über -- in diesem Fall -- Subreddit-Grenzen hinweg.
Zudem könnte der gesamte Prozess umgekehrt werden und ein einzelnes Subreddit in verschiedene Topics gegliedert werden.
Das Resultat wären unterschiedliche Strömungen desselben Themas, was insbesondere bei politischen, wissenschaftlichen oder technischen Subreddits interessante Aspekte beleuchten könnte.

### Ausblick

Während der Bearbeitung ergaben sich zudem weitere Ideen für mögliche Forschungsarbeit, die in diesem letzten Abschnitt noch einmal zur Sprache gebracht werden sollen.

Forschung zu OSN ermöglicht es, das Verhalten der Nutzer besser zu evrstehen und unter Umständen auch vorhersagen zu können.
Damit kann eine Anpassung der Plattform an die Bedürfnisse der Nutzer realisiert werden.
Ein möglicher Ansatz, der sich aus dieser Arbeit ergeben hat, ist die Nutzung von Topic-Modellen und dem Wissen über die Kontakte eines Nutzers, um diesem Communities vorzuschlagen.
Ähnlich wie in dieser Arbeit sei dazu zu jedem Nutzer eine Verteilung der Topics bekannt, in denen er Kommentare verfasst.
Ferner werde diese Verteilung auch für alle Alteri im Netzwerk des Nutzers erhoben.
Fasst man die so erhaltenen Verteilungen von Topics als Wahrscheinlichkeitsverteilungen für Kommentare eines Nutzers auf, lässt sich deren Ähnlichkeit bestimmen.
Als Verfahren hierzu kommen etwa Kullback-Leibler- oder Jensen-Shannon-Divergenz in Frage.
Kennt man die Ähnlichkeit der Verteilungen, lassen sich Ego weitere mögliche Topics vorschlagen: "Die Nutzer, mit denen du kommunizierst, interessieren sich für Topic XY, dies könnte auch für dich interessant sein".

Weiterhin lässt sich LDA dazu einsetzen, versteckte Community-Strukturen sichtbar zu machen.
Der generative Prozess der LDA kennt hierzu die latente Verteilung von Communities über alle Subreddits, weist jedem Subreddit eine Community-Verteilung zu und zieht anschließend aus den Nutzern einer Community den tatsächlichen Nutzer des Subreddits.
So erhält man eine Community-Struktur, die sich über Subreddit-Grenzen hinweg erstreckt und stattdessen Nutzer in den Fokus rückt, die häufig gemeinsam in unterschiedlichen Subreddits aktiv sind.
Die Untersuchung dieser Community-Strukturen mit Methoden der sozialen Netzwerkanalyse wäre ein sinnvoller zweiter Schritt.