#!/usr/bin/env Rscript

# Determine top words in topic model.
#
# For the model generated by LDA, determine the top words that characterize a
# topic.
# Makes use of wordmap.txt and model-final.phi, both produced by GibbsLDA++.
# Adjust number of words in `top_words()` call.

source("R/lda/top_words.R")

wm <- read_wordmap("data/lda/wordmap.txt", showProgress = TRUE)
wtm <-
  read_word_topic_distribution("data/lda/model-final.phi", showProgress = TRUE)

tw <- top_words(wtm, wm, n = 500)

rm(wm)

write.csv(x = tw,
          file = "data/lda/top_words.csv",
          row.names = FALSE)
